# Generated by Django 5.1.1 on 2024-10-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologies',
            name='url_logo',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
