# Generated by Django 5.1.1 on 2024-10-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_posts_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='link_repo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
